#!/bin/bash

# Depod Survey - Demo Rejimi (SQLite)
# MySQL olmadan test üçün

echo "======================================"
echo "Depod Survey - Demo Rejimi"
echo "======================================"
echo ""
echo "⚠️  MySQL tapılmadı."
echo ""
echo "📝 Əl ilə quraşdırma təlimatı:"
echo ""
echo "1. MySQL quraşdırın:"
echo "   sudo apt-get install mysql-server"
echo ""
echo "2. Database yaradın:"
echo "   sudo mysql"
echo "   CREATE DATABASE depod_survey;"
echo "   exit;"
echo ""
echo "3. Schema import edin:"
echo "   sudo mysql depod_survey < database/schema.sql"
echo ""
echo "4. config/config.php faylında DB məlumatlarını yeniləyin"
echo ""
echo "5. Serveri işə salın:"
echo "   ./start-server.sh"
echo ""
echo "======================================"
echo ""
echo "📚 Ətraflı məlumat üçün:"
echo "   cat README.md"
echo "   cat INSTALL.md"
echo ""
